import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

import githubMarkdownCss from 'generate-github-markdown-css'
import { type Declaration, type Rule, parse } from 'postcss'

const BLOCK = '.github-markdown'
const EDITOR_LIGHT = ':where(.vscode-light, .vscode-high-contrast-light)'
const EDITOR_DARK = ':where(.vscode-dark, .vscode-high-contrast:not(.vscode-high-contrast-light))'

const THEMES = [
  'light',
  'light_high_contrast',
  'light_colorblind',
  'light_tritanopia',
  'dark',
  'dark_high_contrast',
  'dark_colorblind',
  'dark_tritanopia',
  'dark_dimmed',
]

const OUTPUT_DIR = join(import.meta.dirname, '..', 'dist', 'features', 'github-markdown')

const header = (summary: string) => `/*
 * Generated by scripts/generate-github-markdown.mts. Do not edit.
 * ${summary}
 */
`

const declarations = (rule: Rule, indent: string) =>
  rule.nodes
    .filter((node): node is Declaration => node.type === 'decl')
    .map(node => `${indent}  ${node.prop}: ${node.value};`)
    .join('\n')

const ruleText = (selectors: string[], rule: Rule, indent = '') =>
  `${selectors.map(selector => `${indent}${selector}`).join(',\n')} {\n${declarations(rule, indent)}\n${indent}}`

const mediaText = (scheme: string, selectors: string[], rule: Rule) =>
  `@media (prefers-color-scheme: ${scheme}) {\n${ruleText(selectors, rule, '  ')}\n}`

const splitVariables = (css: string) => {
  const root = parse(css)
  let tokens: Rule | undefined
  let palette: Rule | undefined

  root.walkRules(rule => {
    if (rule.selectors.some(selector => selector.startsWith('[data-theme'))) palette = rule
    else tokens = rule
  })

  if (!tokens || !palette) throw new Error('Unexpected variable stylesheet shape')
  return { palette, tokens }
}

const withoutDeadRules = (css: string) => {
  const root = parse(css)
  root.walkRules(rule => {
    if (rule.selectors.some(selector => selector.includes(':is()'))) rule.remove()
  })
  return root.toString().trim()
}

const themeStylesheet = (theme: string, palette: Rule) =>
  [
    ruleText(
      [
        `${BLOCK}[data-color-mode='light'][data-light-theme='${theme}']`,
        `${BLOCK}[data-color-mode='dark'][data-dark-theme='${theme}']`,
        `${EDITOR_LIGHT} ${BLOCK}[data-color-mode='auto'][data-light-theme='${theme}']`,
        `${EDITOR_DARK} ${BLOCK}[data-color-mode='auto'][data-dark-theme='${theme}']`,
      ],
      palette
    ),
    mediaText('light', [`${BLOCK}[data-color-mode='system'][data-light-theme='${theme}']`], palette),
    mediaText('dark', [`${BLOCK}[data-color-mode='system'][data-dark-theme='${theme}']`], palette),
  ].join('\n\n')

const save = async (name: string, summary: string, css: string) => {
  await writeFile(join(OUTPUT_DIR, name), `${header(summary)}\n${css}\n`)
  console.info(`Wrote dist/features/github-markdown/${name}`)
}

const themeStylesheets = async () => {
  const themes = []

  for (const theme of THEMES) {
    const variables = await githubMarkdownCss({ dark: theme, light: theme, onlyVariables: true })
    themes.push({ theme, ...splitVariables(variables) })
  }

  const [{ tokens }] = themes
  return [ruleText([BLOCK], tokens), ...themes.map(({ palette, theme }) => themeStylesheet(theme, palette))].join(
    '\n\n'
  )
}

export const generateGithubMarkdown = async () => {
  await mkdir(OUTPUT_DIR, { recursive: true })
  const markdown = await githubMarkdownCss({ onlyStyles: true, rootSelector: BLOCK })
  await save('markdown.css', "GitHub's markdown styles, rooted at .github-markdown.", withoutDeadRules(markdown))
  await save('themes.css', "GitHub's design tokens for every supported theme and color mode.", await themeStylesheets())
}
