import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

import githubMarkdownCss from 'generate-github-markdown-css'
import { type Declaration, type Rule, parse } from 'postcss'

const BLOCK = '.markdown'
const CONTENT = '.markdown__content'
const MARKER = '--markdown-theme'
const EDITOR_LIGHT = ':where(.vscode-light, .vscode-high-contrast-light)'
const EDITOR_DARK = ':where(.vscode-dark, .vscode-high-contrast:not(.vscode-high-contrast-light))'

const THEMES = [
  'light',
  'light_high_contrast',
  'light_colorblind',
  'light_tritanopia',
  'dark',
  'dark_high_contrast',
  'dark_colorblind',
  'dark_tritanopia',
  'dark_dimmed',
]

const OUTPUT_DIR = join(import.meta.dirname, '..', 'dist', 'features', 'markdown')

const themeId = (theme: string) => `github-${theme.replaceAll('_', '-')}`

const header = (summary: string) => `/*
 * Generated by scripts/generate-github-markdown.mts. Do not edit.
 * ${summary}
 */
`

const toPixels = (value: string) => value.replaceAll(/(\d*\.?\d+)rem/g, (_, size: string) => `${Number(size) * 16}px`)

const declarations = (rule: Rule, indent: string) =>
  rule.nodes
    .filter((node): node is Declaration => node.type === 'decl')
    .map(node => `${indent}  ${node.prop}: ${toPixels(node.value)};`)
    .join('\n')

const ruleText = (selectors: string[], body: string, indent = '') =>
  `${selectors.map(selector => `${indent}${selector}`).join(',\n')} {\n${body}\n${indent}}`

const paletteText = (selectors: string[], rule: Rule | undefined, indent = '') => {
  const marker = `${indent}  ${MARKER}: ${rule ? 'github' : 'default'};`
  return ruleText(selectors, rule ? `${declarations(rule, indent)}\n${marker}` : marker, indent)
}

const splitVariables = (css: string) => {
  const root = parse(css)
  let tokens: Rule | undefined
  let palette: Rule | undefined

  root.walkRules(rule => {
    if (rule.selectors.some(selector => selector.startsWith('[data-theme'))) palette = rule
    else tokens = rule
  })

  if (!tokens || !palette) throw new Error('Unexpected variable stylesheet shape')
  return { palette, tokens }
}

const withoutDeadRules = (css: string) => {
  const root = parse(css)
  root.walkRules(rule => {
    if (rule.selectors.some(selector => selector.includes(':is()'))) rule.remove()
  })
  root.walkDecls(declaration => {
    declaration.value = toPixels(declaration.value)
  })
  return root.toString().trim()
}

const contained = (css: string) => `@container style(${MARKER}: github) {\n${css.replaceAll(/^(?!$)/gm, '  ')}\n}`

const themeStylesheet = (theme: string, palette?: Rule) =>
  [
    paletteText(
      [
        `${BLOCK}[data-theme-mode='light'][data-light-theme='${theme}']`,
        `${BLOCK}[data-theme-mode='dark'][data-dark-theme='${theme}']`,
        `${EDITOR_LIGHT} ${BLOCK}[data-theme-mode='auto'][data-light-theme='${theme}']`,
        `${EDITOR_DARK} ${BLOCK}[data-theme-mode='auto'][data-dark-theme='${theme}']`,
      ],
      palette
    ),
    `@media (prefers-color-scheme: light) {\n${paletteText([`${BLOCK}[data-theme-mode='system'][data-light-theme='${theme}']`], palette, '  ')}\n}`,
    `@media (prefers-color-scheme: dark) {\n${paletteText([`${BLOCK}[data-theme-mode='system'][data-dark-theme='${theme}']`], palette, '  ')}\n}`,
  ].join('\n\n')

const save = async (name: string, summary: string, css: string) => {
  await writeFile(join(OUTPUT_DIR, name), `${header(summary)}\n${css}\n`)
  console.info(`Wrote dist/features/markdown/${name}`)
}

const themeStylesheets = async () => {
  const themes = []

  for (const theme of THEMES) {
    const variables = await githubMarkdownCss({ dark: theme, light: theme, onlyVariables: true })
    themes.push({ theme, ...splitVariables(variables) })
  }

  const [{ tokens }] = themes
  return [
    ruleText([BLOCK], declarations(tokens, '')),
    themeStylesheet('default'),
    ...themes.map(({ palette, theme }) => themeStylesheet(themeId(theme), palette)),
  ].join('\n\n')
}

export const generateGithubMarkdown = async () => {
  await mkdir(OUTPUT_DIR, { recursive: true })
  const markdown = await githubMarkdownCss({ onlyStyles: true, rootSelector: CONTENT })
  await save(
    'markdown.css',
    `GitHub's markdown styles, rooted at ${CONTENT} and gated on the ${MARKER} container.`,
    contained(withoutDeadRules(markdown))
  )
  await save('themes.css', "GitHub's design tokens for every supported theme and color mode.", await themeStylesheets())
}
